#!/bin/bash 

# Archive logs from the CLI with the date and time.

# Get Date and time 
timestamp="$(date "+%H%M%S_%d%m%y")"

# Create Tarball 
tar czfv log_archive_$timestamp.tar.gz $1

# See inside tarball without extrcting 
# tar -tf test.tar.gz